SET DEFINE OFF;
SET AUTOCOMMIT OFF;
SET SQLBLANKLINES ON;
SET ECHO ON;

-- first clean-up (keyword url not active)
DELETE FROM SEOURLKEYWORD
WHERE SEOURLKEYWORD_ID 
IN (SELECT SEOURLKEYWORD.SEOURLKEYWORD_ID
 FROM SEOURLKEYWORD
 LEFT JOIN SEOURL ON SEOURLKEYWORD.SEOURL_ID = SEOURL.SEOURL_ID
 WHERE SEOURL.TOKENNAME = 'CategoryToken'
 AND SEOURLKEYWORD.STATUS = 0);

-- second clean-up (keyword url assigned to catgroup mark as deleted)
DELETE FROM SEOURL
WHERE SEOURL_ID 
IN (SELECT DISTINCT SEOURL.SEOURL_ID FROM SEOURL 
 LEFT JOIN SEOURLKEYWORD ON SEOURLKEYWORD.SEOURL_ID = SEOURL.SEOURL_ID
 WHERE SEOURL.TOKENNAME = 'CategoryToken'
 AND SEOURL.TOKENVALUE 
 IN (SELECT CATGROUP_ID FROM CATGROUP WHERE MARKFORDELETE = 1)); 

-- third clean-up (keyword url assigned to catgroup already deleted)
DELETE FROM SEOURL WHERE TOKENNAME = 'CategoryToken' and TOKENVALUE NOT IN (SELECT CATGROUP_ID from CATGROUP);
 
COMMIT;
EXIT;