SET DEFINE OFF;
SET AUTOCOMMIT OFF;
SET SQLBLANKLINES ON;
SET ECHO ON;

DELETE
FROM SEOURL
WHERE SEOURL_ID IN
  ( SELECT DISTINCT SEOURL.SEOURL_ID
    FROM SEOURL
        LEFT JOIN SEOURLKEYWORD ON SEOURLKEYWORD.SEOURL_ID = SEOURL.SEOURL_ID
    WHERE
        SEOURL.TOKENNAME = 'ProductToken'
        AND SEOURL.TOKENVALUE IN
        (SELECT CATENTRY_ID || '' AS CATENTRY_ID FROM CATENTRY WHERE CATENTRY.MARKFORDELETE = 1)
  );
COMMIT;

DELETE
FROM SEOURLKEYWORD
WHERE SEOURLKEYWORD_ID IN
  ( SELECT SEOURLKEYWORD.SEOURLKEYWORD_ID
    FROM SEOURLKEYWORD
        LEFT JOIN SEOURL ON SEOURLKEYWORD.SEOURL_ID = SEOURL.SEOURL_ID
    WHERE
        SEOURL.TOKENNAME = 'ProductToken'
        AND SEOURLKEYWORD.STATUS = 0
  );
  
COMMIT;
EXIT;